export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const TOGGLE_INGREDIENT = "TOGGLE_INGREDIENT";
export const ERROR_LOADING_INGREDIENTS = "ERROR_LOADING_INGREDIENTS";

export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";
export const START_ORDER = "START_ORDER";

export const PURCHASE_INIT = "PURCHASE_INIT";