export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const TOGGLE_INGREDIENT = "TOGGLE_INGREDIENT";
export const ERROR_LOADING_INGREDIENTS = "ERROR_LOADING_INGREDIENTS";

export const BUYPIZZA_SUCCESS = "BUYPIZZA_SUCCESS";
export const BUYPIZZA_FAILED = "BUYPIZZA_FAILED";
export const BUYPIZZA_START = "BUYPIZZA_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const ORDERS_START = "ORDERS_START";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAILED = "ORDERS_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";